package SWP391.Fall24.service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

import java.time.LocalDate;

@Service
public class EmailService {
    @Autowired
    private JavaMailSender mailSender;

    public void sendMail(String to, String subject, String text) throws MessagingException {
        MimeMessage mimeMessage = mailSender.createMimeMessage();
        mimeMessage.setFrom("koifarmshopswp391@gmail.com");
        mimeMessage.addRecipient(MimeMessage.RecipientType.TO, new InternetAddress(to));
        mimeMessage.setSubject(subject);
        mimeMessage.setContent(text, "text/html;charset=utf-8");
        mailSender.send(mimeMessage);
    }

    public String subjectOrder(String fullName) {
        return "Hi, " + fullName + ", thanks for your order from Shoe For Men Shop!";
    }

    public String subjectForgotPass() {
        return "Support forgot password";
    }


//    public String messageOrder(LocalDate date, double totalMoney, String address) {
//        return "<!DOCTYPE html>\n"
//                + "<html lang=\"en\">\n"
//                + "<head>\n"
//                + "  <meta charset=\"utf-8\">\n"
//                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n"
//                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
//                + "  <style>\n"
//                + "    body {\n"
//                + "      font-family: Arial, sans-serif;\n"
//                + "      background-color: #f4f4f4;\n"
//                + "      margin: 0;\n"
//                + "      padding: 0;\n"
//                + "    }\n"
//                + "\n"
//                + "    .email-container {\n"
//                + "      max-width: 600px;\n"
//                + "      margin: 20px auto;\n"
//                + "      background-color: #fff;\n"
//                + "      border-radius: 8px;\n"
//                + "      overflow: hidden;\n"
//                + "      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n"
//                + "    }\n"
//                + "\n"
//                + "    .header {\n"
//                + "      background-color: #3498db;\n"
//                + "      color: #fff;\n"
//                + "      padding: 20px;\n"
//                + "      text-align: center;\n"
//                + "    }\n"
//                + "\n"
//                + "    .content {\n"
//                + "      padding: 20px;\n"
//                + "    }\n"
//                + "\n"
//                + "    .discount-code {\n"
//                + "      background-color: #e74c3c;\n"
//                + "      color: #fff;\n"
//                + "      padding: 10px;\n"
//                + "      text-align: center;\n"
//                + "      margin-bottom: 20px;\n"
//                + "      font-size: 20px;\n"
//                + "      border-radius: 4px;\n"
//                + "    }\n"
//                + "\n"
//                + "    .footer {\n"
//                + "      background-color: #3498db;\n"
//                + "      color: #fff;\n"
//                + "      padding: 10px;\n"
//                + "      text-align: center;\n"
//                + "    }\n"
//                + "  </style>\n"
//                + "</head>\n"
//                + "<body>\n"
//                + "  <div class=\"email-container\">\n"
//                + "    <div class=\"header\">\n"
//                + "     <h1>Koi Farm Shop</h1>\n"
//                + "      <h2>Your order is on its way!</h2>\n"
//                + "    </div>\n"
//                + "    <div class=\"content\">\n"
//                + "      <h3>Order summary:</h3>\n"
//                + "      <p>Order Date: " + date + "</p>\n"
//                + "      <p>Order Total: " + totalMoney + "$</p>\n"
//                + "      <p>Shipping address: " + address + "</p>\n"
//                + "      <p>If you have any questions, contact us here or call us on 0773363666.</p>\n"
//                + "      <p>We are here to help!</p>\n"
//                + "    </div>\n"
//                + "    <div class=\"footer\">\n"
//                + "      <p>Thank you for placing your order!</p>\n"
//                + "    </div>\n"
//                + "  </div>\n"
//                + "</body>\n"
//                + "</html>";
//    }

//    public String messageOrder(LocalDate date, double totalMoney, String address, String status) {
//        // Determine which steps should be marked as completed based on the current status
//        String step1 = status.equals("Đợi Xác Nhận") || status.equals("Đang Chuẩn Bị") || status.equals("Đang Vận Chuyển") || status.equals("Đã Hoàn Thành") ? "completed" : "";
//        String step2 = status.equals("Đang Chuẩn Bị") || status.equals("Đang Vận Chuyển") || status.equals("Đã Hoàn Thành") ? "completed" : "";
//        String step3 = status.equals("Đang Vận Chuyển") || status.equals("Đã Hoàn Thành") ? "completed" : "";
//        String step4 = status.equals("Đã Hoàn Thành") ? "completed" : "";
//        String activeStep = status;
//
//        return "<!DOCTYPE html>\n"
//                + "<html lang=\"en\">\n"
//                + "<head>\n"
//                + "  <meta charset=\"utf-8\">\n"
//                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n"
//                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
//                + "  <style>\n"
//                + "    body {\n"
//                + "      font-family: Arial, sans-serif;\n"
//                + "      background-color: #f4f4f4;\n"
//                + "      margin: 0;\n"
//                + "      padding: 0;\n"
//                + "    }\n"
//                + "    .email-container {\n"
//                + "      max-width: 600px;\n"
//                + "      margin: 20px auto;\n"
//                + "      background-color: #fff;\n"
//                + "      border-radius: 8px;\n"
//                + "      overflow: hidden;\n"
//                + "      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n"
//                + "    }\n"
//                + "    .header {\n"
//                + "      background-color: #3498db;\n"
//                + "      color: #fff;\n"
//                + "      padding: 20px;\n"
//                + "      text-align: center;\n"
//                + "    }\n"
//                + "    .content {\n"
//                + "      padding: 20px;\n"
//                + "    }\n"
//                + "    .progress-container {\n"
//                + "      display: flex;\n"
//                + "      align-items: center;\n"
//                + "      justify-content: space-between;\n"
//                + "      max-width: 100%;\n"
//                + "      margin: 20px 0;\n"
//                + "    }\n"
//                + "    .progress-step {\n"
//                + "      text-align: center;\n"
//                + "      position: relative;\n"
//                + "      flex: 1;\n"
//                + "    }\n"
//                + "    .progress-step:not(:last-child)::after {\n"
//                + "      content: \"\";\n"
//                + "      position: absolute;\n"
//                + "      top: 50%;\n"
//                + "      right: -50%;\n"
//                + "      width: 100%;\n"
//                + "      height: 4px;\n"
//                + "      background-color: #ccc;\n"
//                + "      z-index: -1;\n"
//                + "    }\n"
//                + "    .progress-step.completed::after {\n"
//                + "      background-color: green;\n"
//                + "    }\n"
//                + "    .progress-icon {\n"
//                + "      width: 40px;\n"
//                + "      height: 40px;\n"
//                + "      border-radius: 50%;\n"
//                + "      background-color: #ccc;\n"
//                + "      display: flex;\n"
//                + "      align-items: center;\n"
//                + "      justify-content: center;\n"
//                + "      color: #fff;\n"
//                + "      font-size: 24px;\n"
//                + "      margin: 0 auto;\n"
//                + "    }\n"
//                + "    .progress-step.completed .progress-icon {\n"
//                + "      background-color: green;\n"
//                + "    }\n"
//                + "    .progress-text {\n"
//                + "      margin-top: 8px;\n"
//                + "      font-weight: bold;\n"
//                + "    }\n"
//                + "    .progress-step.completed .progress-text {\n"
//                + "      color: green;\n"
//                + "    }\n"
//                + "  </style>\n"
//                + "</head>\n"
//                + "<body>\n"
//                + "  <div class=\"email-container\">\n"
//                + "    <div class=\"header\">\n"
//                + "      <h1>Koi Farm Shop</h1>\n"
//                + "      <h2>Your order is on its way!</h2>\n"
//                + "    </div>\n"
//                + "    <div class=\"content\">\n"
//                + "      <h3>Order summary:</h3>\n"
//                + "      <p>Order Date: " + date + "</p>\n"
//                + "      <p>Order Total: " + totalMoney + "$</p>\n"
//                + "      <p>Shipping address: " + address + "</p>\n"
//                + "      <div class=\"progress-container\">\n"
//                + "        <div class=\"progress-step " + step1 + "\">\n"
//                + "          <div class=\"progress-icon\"></div>\n"
//                + "          <div class=\"progress-text\">Đợi Xác Nhận</div>\n"
//                + "        </div>\n"
//                + "        <div class=\"progress-step " + step2 + "\">\n"
//                + "          <div class=\"progress-icon\"></div>\n"
//                + "          <div class=\"progress-text\">Đang Chuẩn Bị</div>\n"
//                + "        </div>\n"
//                + "        <div class=\"progress-step " + step3 + "\">\n"
//                + "          <div class=\"progress-icon\"></div>\n"
//                + "          <div class=\"progress-text\">Đang Vận Chuyển</div>\n"
//                + "        </div>\n"
//                + "        <div class=\"progress-step " + step4 + "\">\n"
//                + "          <div class=\"progress-icon\"></div>\n"
//                + "          <div class=\"progress-text\">Đã Hoàn Thành</div>\n"
//                + "        </div>\n"
//                + "      </div>\n"
//                + "      <p>If you have any questions, contact us here or call us on 0773363666.</p>\n"
//                + "      <p>We are here to help!</p>\n"
//                + "    </div>\n"
//                + "    <div class=\"footer\">\n"
//                + "      <p>Thank you for placing your order!</p>\n"
//                + "    </div>\n"
//                + "  </div>\n"
//                + "</body>\n"
//                + "</html>";
//    }

    public String messageOrder(LocalDate date, double totalMoney, String address, String status) {
        String step1 = status.equals("Đợi Xác Nhận") || status.equals("Đang Chuẩn Bị") || status.equals("Đang Vận Chuyển") || status.equals("Đã Hoàn Thành") ? "completed" : "";
        String step2 = status.equals("Đang Chuẩn Bị") || status.equals("Đang Vận Chuyển") || status.equals("Đã Hoàn Thành") ? "completed" : "";
        String step3 = status.equals("Đang Vận Chuyển") || status.equals("Đã Hoàn Thành") ? "completed" : "";
        String step4 = status.equals("Đã Hoàn Thành") ? "completed" : "";

        return "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "  <style>\n"
                + "    body {\n"
                + "      font-family: Arial, sans-serif;\n"
                + "      background-color: #f9f9f9;\n"
                + "      margin: 0;\n"
                + "      padding: 0;\n"
                + "      color: #333;\n"
                + "    }\n"
                + "    .email-container {\n"
                + "      max-width: 600px;\n"
                + "      margin: 20px auto;\n"
                + "      background-color: #ffffff;\n"
                + "      border-radius: 8px;\n"
                + "      overflow: hidden;\n"
                + "      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\n"
                + "    }\n"
                + "    .header {\n"
                + "      background-color: #3498db;\n"
                + "      color: #ffffff;\n"
                + "      padding: 20px;\n"
                + "      text-align: center;\n"
                + "      font-size: 24px;\n"
                + "    }\n"
                + "    .content {\n"
                + "      padding: 20px;\n"
                + "      text-align: center;\n"
                + "      font-size: 16px;\n"
                + "    }\n"
                + "    .progress-container {\n"
                + "      display: flex;\n"
                + "      justify-content: space-between;\n"
                + "      align-items: center;\n"
                + "      padding: 20px 0;\n"
                + "    }\n"
                + "    .progress-step {\n"
                + "      text-align: center;\n"
                + "      flex: 1;\n"
                + "      padding: 0 10px;\n"
                + "      position: relative;\n"
                + "    }\n"
                + "    .progress-step::after {\n"
                + "      content: '';\n"
                + "      position: absolute;\n"
                + "      top: 20px;\n"
                + "      left: 50%;\n"
                + "      transform: translateX(-50%);\n"
                + "      width: 80%;\n"
                + "      height: 4px;\n"
                + "      background-color: #ddd;\n"
                + "      z-index: -1;\n"
                + "    }\n"
                + "    .progress-step.completed::after {\n"
                + "      background-color: #28a745;\n"
                + "    }\n"
                + "    .progress-icon {\n" +
                "    width: 40px;\n" +
                "    height: 40px;\n" +
                "    border-radius: 50%;\n" +
                "    background-color: #ddd;\n" +
                "    display: flex;\n" +
                "    align-items: center;\n" +
                "    justify-content: center;\n" +
                "    color: #fff;\n" +
                "    font-size: 18px;\n" +
                "    margin: 0 auto 10px;\n" +
                "    padding: auto;\n"+
                "    line-height: 1; /* Ensures the icon stays centered vertically */\n" +
                "}\n"
                + "    .progress-step.completed .progress-icon {\n"
                + "      background-color: #28a745;\n"
                + "    }\n"
                + "    .progress-text {\n"
                + "      font-weight: 600;\n"
                + "      color: #555;\n"
                + "      margin-top: 5px;\n"
                + "    }\n"
                + "    .footer {\n"
                + "      background-color: #3498db;\n"
                + "      color: #ffffff;\n"
                + "      padding: 15px;\n"
                + "      text-align: center;\n"
                + "      font-size: 14px;\n"
                + "      border-radius: 0 0 8px 8px;\n"
                + "    }\n"
                + "    .footer-button {\n"
                + "      display: inline-block;\n"
                + "      padding: 10px 20px;\n"
                + "      color: #ffffff;\n"
                + "      background-color: #3498db;\n"
                + "      border-radius: 5px;\n"
                + "      text-decoration: none;\n"
                + "      font-weight: bold;\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "  <div class=\"email-container\">\n"
                + "    <div class=\"header\">\n"
                + "      <h1>Koi Farm Shop</h1>\n"
                + "      <h2>Your order is on its way!</h2>\n"
                + "    </div>\n"
                + "    <div class=\"content\">\n"
                    + "      <h3>ORDER SUMMARY</h3>\n"
                + "      <p>Order Date: " + date + "</p>\n"
                + "      <p>Order Total: VND" + totalMoney + "</p>\n"
                + "      <p>Shipping address: " + address + "</p>\n"
                    + "      <h3>ORDER PROCESS</h3>\n"
                + "      <div class=\"progress-container\">\n"
                + "        <div class=\"progress-step " + step1 + "\">\n"
                + "          <div class=\"progress-icon\">✔</div>\n"
                + "          <div class=\"progress-text\">Đợi Xác Nhận</div>\n"
                + "        </div>\n"
                + "        <div class=\"progress-step " + step2 + "\">\n"
                + "          <div class=\"progress-icon\">✔</div>\n"
                + "          <div class=\"progress-text\">Đang Chuẩn Bị</div>\n"
                + "        </div>\n"
                + "        <div class=\"progress-step " + step3 + "\">\n"
                + "          <div class=\"progress-icon\">✔</div>\n"
                + "          <div class=\"progress-text\">Đang Vận Chuyển</div>\n"
                + "        </div>\n"
                + "        <div class=\"progress-step " + step4 + "\">\n"
                + "          <div class=\"progress-icon\">✔</div>\n"
                + "          <div class=\"progress-text\">Đã Hoàn Thành</div>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "      <p>If you have any questions, contact us here or call us on 0773363666.</p>\n"
                + "      <p>We are here to help!</p>\n"
                + "    </div>\n"
                + "    <div class=\"footer\">\n"
                + "      <a href=\"#\" class=\"footer-button\">Thank you for placing your order!</a>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</body>\n"
                + "</html>";
    }





    public String messageForgotPass(String name, int code) {
        return "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Password Reset Code</title>\n"
                + "</head>\n"
                + "<body style=\"font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;\">\n"
                + "\n"
                + "    <table style=\"width: 100%; max-width: 600px; margin: 20px auto; background-color: #ffffff; border-collapse: collapse;\">\n"
                + "        <tr>\n"
                + "            <td style=\"padding: 20px; text-align: center; background-color: #4CAF50; color: #ffffff; font-size: 24px;\">\n"
                + "                Password Reset Code\n"
                + "            </td>\n"
                + "        </tr>\n"
                + "        <tr>\n"
                + "            <td style=\"padding: 20px;\">\n"
                + "                <p>Hello " + name + ",</p>\n"
                + "                <p>You have requested to reset your password. Please use the following code to reset your password:</p>\n"
                + "                <p style=\"font-size: 28px; font-weight: bold; color: #4CAF50;\">" + code + "</p>\n"
                + "                <p>If you didn't request this, you can safely ignore this email.</p>\n"
                + "                <p>Thank you!</p>\n"
                + "            </td>\n"
                + "        </tr>\n"
                + "        <tr>\n"
                + "            <td style=\"padding: 20px; text-align: center; background-color: #4CAF50; color: #ffffff;\">\n"
                + "                &copy; 2024 Koi Paradise\n"
                + "            </td>\n"
                + "        </tr>\n"
                + "    </table>\n"
                + "\n"
                + "</body>\n"
                + "</html>";
    }
}
